name: CPU Data Scraper

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  scrape-and-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run CPU scraper
        run: |
          python3 cpubenchmarkapi.py -i cpus.txt -o cpuData.csv

      - name: Verify CSV file
        run: |
          echo "Checking if cpuData.csv exists..."
          if [ -f "cpuData.csv" ]; then
            echo "File exists!"
            ls -lh cpuData.csv  # 显示文件大小
            cat cpuData.csv | head -n 5  # 输出文件前5行，确认内容
          else
            echo "Error: cpuData.csv not found!"
            exit 1
          fi

      - name: Upload CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: cpu-data
          path: cpuData.csv
          if-no-files-found: error  # 如果文件不存在，直接报错

      - name: Create Release and Upload CSV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="v$(date +'%Y%m%d-%H%M%S')"
          timeout 5m gh release create "$TAG_NAME" \
            --title "CPU Data $TAG_NAME" \
            --notes "Automated CPU benchmark data scrape from $(date)" \
            --draft=false || echo "Release creation timed out"
          timeout 5m gh release upload "$TAG_NAME" cpuData.csv || echo "Upload timed out"
